version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:root@mysql-cogna:3306/cogna
    volumes:
      - ./backend:/app
    depends_on:
      - mysql-cogna
    restart: unless-stopped

  
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
    restart: unless-stopped
    depends_on:
      - backend

  mysql-cogna:
    image: mysql:8.0
    restart: unless-stopped
    container_name: mysql-cogna
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cogna
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data: